create table tb_game (
    game_year integer,
    score float(53),
    id bigint generated by default as identity,
    genre varchar(255),
    img_url varchar(255),
    long_description TEXT,
    platforms varchar(255),
    short_description TEXT,
    title varchar(255),
    primary key (id)
);